version: "3.9"
services:
  postgres:
    # postgres:15.1-alpine は postgres:15.1 と比較して、イメージサイズ小
    image: postgres:15.1-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
